window.downloadClientTicket = async (serviceId) => {
    const docSnap = await getDoc(doc(db, "rescates", serviceId));
    if (!docSnap.exists()) return;
    const data = docSnap.data();
    const { jsPDF } = window.jspdf;
    const pdfDoc = new jsPDF();
    pdfDoc.setFillColor(255, 107, 0);
    pdfDoc.rect(0, 0, 210, 30, 'F');
    pdfDoc.setFontSize(18);
    pdfDoc.setTextColor(255, 255, 255);
    pdfDoc.text("COMPROBANTE DE SERVICIO OBR", 14, 18);
    pdfDoc.setTextColor(0, 0, 0);
    pdfDoc.setFontSize(10);
    pdfDoc.text(`Servicio: ${data.shortId || 'Sin ID'}`, 14, 40);
    pdfDoc.text(`Cliente: ${window.currentUserDoc?.name || ''}`, 14, 46);
    pdfDoc.text(`Moto: ${data.marca || ''} ${data.modelo || ''}`, 14, 52);
    pdfDoc.text(`Fecha: ${new Date(data.timestamp).toLocaleString()}`, 14, 58);
    const lines = pdfDoc.splitTextToSize(`Descripción: ${data.falla}`, 180);
    pdfDoc.text(lines, 14, 65);
    let y = 65 + (lines.length * 6);
    pdfDoc.text(`Estado: ${data.status}`, 14, y);
    if (data.costoRescateEstimado) pdfDoc.text(`Costo: $${data.costoRescateEstimado}`, 14, y + 6);
    pdfDoc.save(`Servicio_${data.shortId || serviceId}.pdf`);
};
